# Form implementation generated from reading ui file 'ui\detail.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(315, 230)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(30, 30, 49, 16))
        self.label.setObjectName("label")
        self.idLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.idLineEdit.setGeometry(QtCore.QRect(80, 30, 221, 22))
        self.idLineEdit.setObjectName("idLineEdit")
        self.titleLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.titleLineEdit.setGeometry(QtCore.QRect(80, 60, 221, 22))
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 49, 16))
        self.label_2.setObjectName("label_2")
        self.priceLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.priceLineEdit.setGeometry(QtCore.QRect(80, 90, 221, 22))
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 49, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 150, 75, 24))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Detail"))
        self.label.setText(_translate("Form", "Id: "))
        self.label_2.setText(_translate("Form", "Title:"))
        self.label_3.setText(_translate("Form", "Price:"))
        self.pushButton.setText(_translate("Form", "Save"))
